version: 2

machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image: docker
    branches:
      only:
        - azure-ad
    steps:
      - checkout
      - setup_remote_docker
      - run: docker info
      - run: docker build -t flaccid/openvpn:azure-ad .
      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push flaccid/openvpn:azure-ad
