version: 2

machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image: docker
    branches:
      only:
        - azure-ad
    steps:
      - checkout
      - setup_remote_docker
      - run: docker info
      - run:
          name: Build docker image
          command: |
            docker build -t flaccid/openvpn:azure-ad .
      - deploy:
          name: Push to Docker Hub
          command: |
            docker login --username=\"$DOCKER_USER\" --password=\"$DOCKER_PASS\"
            docker push flaccid/openvpn:azure-ad
