version: 2

machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image: flaccid/openvpn:azure-ad
    steps:
      - checkout
      - docker info
      - docker build -t flaccid/openvpn:azure-ad .
    deployment:
      hub:
        branch: azure-ad
        commands:
          - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
          - docker push flaccid/openvpn:azure-ad
